# -------------------------
# GLOBAL SETTINGS
# -------------------------
add_newline = true

# Line 1: left (git, venv, cwd) + right (k8s, battery, time)
# Line 2: prompt symbol only
format = """
$git_branch( ≻$git_status)( ≻$python)( ≻$directory)$fill(≺$kubernetes )(≺$battery )(≺$time)
$character
"""

# -------------------------
# MODULE CONFIG
# -------------------------

[directory]
style = "bold fg:#585858" # CWD_THEME_PROMPT_COLOR=240
truncation_length = 3
read_only = " "
format = " [$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = " [$symbol$branch]($style)"
symbol = " " # SCM_GIT_CHAR
style = "bold fg:#005f5f" # SCM_THEME_PROMPT_CLEAN_COLOR=25

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "fg:#870000" # SCM_THEME_PROMPT_DIRTY_COLOR=88

[python]
format = " [$symbol$virtualenv](style)"
detect_extensions = []
detect_files = []
style = "bold fg:#00af5f" # PYTHON_VENV_THEME_PROMPT_COLOR=35

[kubernetes]
disabled = false
format = " [⎈ $context]($style)"
style = "fg:#d70087" # KUBE_THEME_PROMPT_COLOR=161

[battery]
disabled = false
format = " [$symbol$percentage]($style)"
discharging_symbol = ""

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 40
style = 'bold fg:#ffaf00'

[[battery.display]] # show battery for anything up to 100%
threshold = 100
style = 'bold fg:#5faf00'


[time]
disabled = false
format = " [$time]($style)"
time_format = "%H:%M" # THEME_CLOCK_FORMAT
style = "fg:#585858 dimmed" # CLOCK_THEME_PROMPT_COLOR=240

[fill]
symbol = " "

[character]
success_symbol = "➜"
error_symbol = "[➜](bold red)"